language: c
sudo: false
compiler: gcc

addons:
  apt:
    packages:
    - libfile-homedir-perl

script:
  - cd libraries/ArduinoTap
  - prove --exec=./runino_pc examples/manual/*.ino
  - prove --exec=./runino_pc examples/diag/*.ino examples/is*/*.ino examples/*ok/*.ino examples/no_plan/*.ino examples/pass/*.ino examples/skip*/*.ino examples/todo/*.ino

branches:
  only:
    - master

